services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    volumes:
      - $MONITOR_WORKSPACE/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json
    ports:
      - 9090:9090
    restart: unless-stopped

  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:latest
    ports:
      - 9091:9091
    restart: unless-stopped

  blackbox_exporter:
    container_name: blackbox_exporter
    image: prom/blackbox-exporter:latest
    command:
      - "--config.file=/etc/blackbox_exporter/blackbox.yml"
    volumes:
      - $MONITOR_WORKSPACE/blackbox_exporter/blackbox.yml:/etc/blackbox_exporter/blackbox.yml
    ports:
      - 9115:9115
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    command:
      - "--config=/etc/grafana/grafana.ini"
    volumes:
      - $MONITOR_WORKSPACE/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - 3000:3000
    restart: unless-stopped

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:latest
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    volumes:
      - $MONITOR_WORKSPACE/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    restart: unless-stopped

  # https://github.com/prometheus/node_exporter?tab=readme-ov-file#docker
  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    restart: unless-stopped
